### ISSUE TITLE
RelationshipResource table row not clickable

### ISSUE THREAD

**Issue by aurawindsurfing** [alexjustesen/filament-spatie-laravel-activitylog#39]
Hi Alex! Thanks for hand package.

I have installed spatie/activity-log few times already. I run migrations and logged first event for User Model.

Then I installed filament-spatie-laravel-activitylog and added relationship manager

`
namespace App\Filament\Resources;
`
`
class UserResource extends Resource
{
`

`use AlexJustesen\FilamentSpatieLaravelActivitylog\RelationManagers\ActivitiesRelationManager;`

    public static function getRelations(): array
    {
        return [
            ActivitiesRelationManager::class
        ];
    }

The log showed up correctly in the UserResource in filamentphp.

The issue I have is that it displays no info about the changes made and it is not clickable - I can see there are views for displaying the details but they are not activated by default.

Thank you for your time!

**Comment by aurawindsurfing** [comment]
Solved! It did not work until I extended your original class. Thank you again for amazing package!

**Comment by rikiless** [comment]
What changes did you make in class? I tried `canView()` with returning `true`, but it didn't help.

**Comment by rikiless** [comment]
I overrided it this way:

```php
public static function table(Table $table): Table
    {
        $table->actions([
            ViewAction::make(),
        ]);

        return ActivityResource::table($table);
    }
```

I got this result. Columns are not aligned properly (centered). How can I fix this?

<img width="1232" alt="Screenshot 2023-01-23 at 15 28 38" src="https://user-images.githubusercontent.com/589851/214064549-4a47fcf7-8737-40c7-9071-80832e4a7bec.png">

**Comment by aurawindsurfing** [comment]
In my case no issues with layout

**Comment by kuldeepBacancy** [comment]
> Solved! It did not work until I extended your original class. Thank you again for amazing package!

Can you share the extended original class details with a little example? I'm getting the same error.
