### ISSUE TITLE
Extend of ActivityRessource

### ISSUE THREAD

**Issue by vdeville** [alexjustesen/filament-spatie-laravel-activitylog#50]
Hello,

To start, thanks for your bundle.

I followed the documentation and make an extend of default bundle ActivityRessource class, changed the config to use this new class but when i extends the `form()` method for example, the parent class is always call.

I'v tried to copy past the full parent class but same problematic, the form() method in my class was never call, it's always the base method of your bundle.

Probably, i do something wrong ?

Bundle version: v0.6.3

Thanks

**Comment by Dawime-dev** [comment]
Hello @vdeville,

If you want to extend ActivityResource, you should override the function `getPages()` and create your own versions of `ListPage` and `ViewPage` and set `protected static string $resource = ActivityResource::class;`

Replace `ActivityResource::class` by your own class.

**Comment by vdeville** [comment]
Thanks @Dawime-dev
